ad2210_planning:
  timezone: 'Europe/Paris'
  locale: 'fr_FR'

  # valeurs par défaut (facultatives)
  toolbar:
    anchor_location: toolbar
    user_selector_location: toolbar
    views: { day: true, week: true, workweek: true, month: true }

  grid:
    work_start: '07:00'
    work_end: '19:00'
    overflow_hours: 2
    now_indicator: true
    highlight_current_day: true
    minute_step: 30
    half_hour_opacity: 0.25
    day_label_format: 'EEE d MMM' # Format ICU
    time_label_format: 'HH:mm' # Format ICU

  modes:
    global:
      toolbar:
        anchor_location: sidebar
        views: { month: true, week: true, workweek: false, day: false }
      grid:
        minute_step: 60

    user:
      toolbar:
        anchor_location: toolbar
        user_selector_location: toolbar
      grid:
        minute_step: 30

    project:
      toolbar:
        anchor_location: toolbar
        user_selector_location: sidebar
      grid:
        overflow_hours: 1
