ad2210_planning:
  timezone: 'Europe/Paris'
  formats:
    day_label:  'EEE dd MMM'
    hour_label: 'HH:mm'
  modes:
    user:
      toolbar:
        show_anchor_picker: true
        show_user_picker: true
        show_project_picker: false
        show_period_picker: true
        anchor_in_sidebar: false
        user_in_sidebar: false
        project_in_sidebar: true
      grid:
        minute_step: 30
        first_hour: 7
        last_hour: 19
        show_now_line: true
      api:
        # on pointe vers l'API de démo créée par make:demo (même host)
        list_url:               '/planning/api/slots?mode=user'
        create_url:             '/planning/api/slots'
        update_url_template:    '/planning/api/slots/{id}'
        duplicate_url_template: '/planning/api/slots/{id}/duplicate'
        delete_url_template:    '/planning/api/slots/{id}'
        csrf_header:            'X-CSRF-TOKEN'
