services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  Ad2210\MultiProjectTeamPlanning\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,Tests}'

  Ad2210\MultiProjectTeamPlanning\Twig\Components\:
    resource: '../../Twig/Components/'
    public: true

  Ad2210\MultiProjectTeamPlanning\Controller\:
    resource: '../../Controller/'
    tags: [ 'controller.service_arguments' ]
    public: true

  Ad2210\MultiProjectTeamPlanning\Command\:
    resource: '../../Command/*'
    public: true